---

name: GitHub job listings check
run-name: "GitHub job listings check for ${{ inputs.country || 'Switzerland' }}"

on:
  workflow_dispatch:
    inputs:
      country:
        description: 'For which country to look for listings'
        required: true
        default: 'Switzerland'
        type: string

  schedule:
    - cron: '*/15 * * * *'

jobs:
  check_listings:
    name: Check Listings
    runs-on: ubuntu-22.04
    env:
      COUNTRY: ${{ inputs.country || 'Switzerland' }}

    steps:
      - name: Fetch content
        id: fetch-content
        env:
          LISTINGS_URL: 'https://boards.greenhouse.io/github'
        run: |
          RESULT=$(curl -s ${{ env.LISTINGS_URL}} | grep -i -B 2 ${{ env.COUNTRY }})

      - name: Notify
        if: ${{ steps.fetch-content.outputs.contentLength > 1 }}
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{ secrets.SMTP_CONNECTION_URL }}
          subject: "Found job listings for ${{ env.COUNTRY }}"
          to: ${{ vars.EMAIL_TO }}
          from: "Radoslav Stoyanov"
          body: ${{ env.EXTRACTED_CONTENT }}